newapp/models.py

from django.db import models
from django.utils import timezone
import random
from django.contrib.auth.models import User
from django.db import models
from datetime import timedelta



class planmdl(models.Model):
    title=models.CharField(max_length=150)
    duration = models.IntegerField(default='')
    description = models.TextField(max_length=1200)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    uploaddate =models.DateTimeField(auto_now_add=True)

class videomdl(models.Model):
    title = models.CharField(max_length=150)
    thumbnail = models.ImageField(upload_to='thumbnails/')  
    video_file = models.FileField(upload_to='videos/')
    description = models.TextField(max_length=1200)
    upload_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phonenumber = models.CharField(max_length=12)  
    email = models.EmailField('') 
    username = models.CharField(max_length=150)  
    password = models.CharField(max_length=128)  
    blocked = models.BooleanField(default=False)
    def __str__(self):
        return self.user.username
    def is_user_subscribed(self, user):
        # Check if the user has an active subscription to any plan associated with this video
        return Subscription.objects.filter(user=user, plan__videomdl=self).exists()

class Subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    plan = models.ForeignKey(planmdl, on_delete=models.CASCADE)
    subscribed_at = models.DateTimeField(auto_now_add=True)
    order_id = models.CharField(max_length=10, unique=True, default='')
    ExpiryDate = models.DateTimeField(blank=True, null=True)
    def save(self, *args, **kwargs):
        if not self.id:
            while True:
                order_id = ''.join(random.choices('0123456789', k=8))
                if not Subscription.objects.filter(order_id=order_id).exists():
                    self.order_id = order_id
                    break

        if self.plan and self.plan.duration is not None:
            if not self.subscribed_at:
                self.subscribed_at = timezone.now()  # Set current time if subscribed_at is None

            self.ExpiryDate = self.subscribed_at + timedelta(days=self.plan.duration)
        else:
            self.ExpiryDate = timezone.now()  # Default to current time if plan or duration is not available

        super().save(*args, **kwargs)

    def is_active(self):
        return self.ExpiryDate > timezone.now()



newapp/templates/createplan.html


{% extends 'layout/app-layout.html' %}
{% block 'content' %}
{%load static %}
<style>
    h1{
    font-size: 45px;
    text-align: center;
    font-weight: 120;
   
    font-family:'Times New Roman', Times, serif;
     color: #2a2443;
    }
</style>
<br>
<h1>
    Hello! Lets,create plans
</h1>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="login-form">
               
                <form method="post" action="">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_title" style="color: azure;font-size:20px ;">Title:</label>
                     <input type="text" name="title" maxlength="150" class="form-control" required=""  placeholder="enter the title" id="id_title">
                             <div class="form-group">
                     <label for="id_duration" style="color: azure;font-size:20px ;">Duration:</label>
                            <input type="number" name="duration" required="" id="id_duration" class="form-control" placeholder="enter the duration">
                                    
                <div class="form-group">
                    <label for="id_description" style="color: azure;font-size:20px ;">Description:</label>
                    <textarea name="description" cols="40" rows="1" maxlength="1200" class="form-control" placeholder="enter the description" required="" id="id_description"></textarea>
                        
                <div class="form-group">
                    <label for="id_price" style="color: azure;font-size:20px ;">Price:</label>
                    <input type="number" name="price" class="form-control" required="" id="id_price">
                        <br>
                                    
                <button type = "submit" value="submit" class = "btn  form-control btn-primary" style="color: rgb(3, 7, 11);" >Submit</button>    </form>



{%endblock%}

newapp/templates/createvideo.html
{% extends 'layout/app-layout.html' %}
{% block 'content' %}
{% load static %}

<style>
    h1 {
        font-size: 45px;
        text-align: center;
        font-weight: 120;
        font-family: 'Times New Roman', Times, serif;
        color: #2a2443;
    }
    .form-group {
        margin-bottom: 15px;
    }
    .form-control {
        padding: 10px;
        border-radius: 5px;
    }
    .btn-primary {
        background-color: #007bff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
    }
</style>

<h1>Hello! Let's create videos.</h1>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="login-form">
                <form method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_title" style="color: azure; font-size: 20px;">Title:</label>
                        <input type="text" name="title" class="form-control" maxlength="150" required placeholder="Enter the title" id="id_title">
                    </div>
                    <div class="form-group">
                        <label for="id_description" style="color: azure; font-size: 20px;">Description:</label>
                        <textarea name="description" cols="40" rows="1" class="form-control" placeholder="Enter the description" maxlength="1200" required id="id_description"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="id_thumbnail" style="color: azure; font-size: 20px;">Thumbnail:</label>
                        <input type="file" name="thumbnail" accept="image/*" required id="id_thumbnail">
                    </div>
                    <div class="form-group">
                        <label for="id_video_file" style="color: azure; font-size: 20px;">Video file:</label>
                        <input type="file" name="video_file" required id="id_video_file">
                    </div>
                    <button type="submit" class="btn btn-primary form-control" style="color: white;">Submit</button>
                    {% if error_message %}
                        <p>{{ error_message }}</p>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

newapp/templates/editvideo.html
{% extends 'layout/app-layout.html' %}
{% block 'content' %}
{% load static %}
<style>
    h1 {
        font-size: 45px;
        text-align: center;
        font-weight: 120;
        font-family: 'Times New Roman', Times, serif;
        color: #2a2443;
    }
</style>
<h1>Hello! Let's Edit this Video.</h1>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="login-form">
                <form method="post" action="{% url 'editvideo' product.id %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_title" style="color: azure; font-size: 20px;">Title:</label>
                        <input type="text" name="title" value="{{ product.title }}" maxlength="150" required class="form-control" id="id_title">
                    </div>
                    <div class="form-group">
                        <label for="id_description" style="color: azure; font-size: 20px;">Description:</label>
                        <textarea name="description" cols="40" rows="1" maxlength="1200" required id="id_description" class="form-control">{{ product.description }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="id_thumbnail">Thumbnail:</label>
                        <input type="file" name="thumbnail" accept="image/*" id="id_thumbnail">
                        {% if product.thumbnail %}
                        <div>
                            <img src="{{ product.thumbnail.url }}" alt="{{ product.title }} thumbnail" width="500" height="250">
                            <p>{{ product.thumbnail.name }}</p>
                        </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label for="video_file" style="color: azure; font-size: 20px; margin-bottom: -10;">Video file:</label>
                        <input type="file" name="video_file" accept="video/*" id="video_file">
                        {% if product.video_file %}
                        <div>
                            <video width="520" height="440" controls>
                                <source src="{{ product.video_file.url }}" type="video/mp4">
                                Your browser does not support the video tag.
                            </video>
                            <p>{{ product.video_file.name }}</p>
                        </div>
                        {% endif %}
                    </div>
                    <button class="btn btn-success form-control" type="submit"  style="color: rgb(3, 7, 11);">Update</button>
                    <br><br>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newapp/templates/home.html

{% extends 'layout/app-layout.html' %}
{% block 'content' %}
{%load static %}
<style>
    
    body{
        background-image: url("{% static 'img1.jpg' %}");
	  /* Adjust background properties as needed */
	  
	  background-repeat: no-repeat;
	  background-size: cover; /* or 'contain' based on your preference */
	  /* Optionally, you can add more CSS properties such as background-position */
	  background-position: center;
            background-size: cover;
            padding-top: 45px;
	  }
      .nav-links {
    list-style: none;
    display: flex;
    
}

.nav-links li {
    margin-right: 20px;
    
}
a{
    color: black;
    font-size: 24px;
}
    h1{
    font-size: 85px;
    text-align: center;
    font-weight: 520;
    margin-top: 100px;
    font-family:'Times New Roman', Times, serif;
     color: #063746;
    }
</style>
</head>
<body>
<nav class="navbar">
    <ul class="nav-links">
        <li><a href="{% url 'createvideo' %}">create video </a></li>
        <li><a href="{% url 'videolists' %}">list videos </a></li>
    </ul>
</nav>

    <h1>
        Hello! Welcome
    </h1>
    
    
</body>
</html>

{%endblock%}




newapp/templates/login.html

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <title>Login</title>
    {% load static %}

    <style>
   body {
	  background-image: url("{% static 'img1.jpg' %}");
	  /* Adjust background properties as needed */
	  
	  background-repeat: no-repeat;
	  background-size: cover; /* or 'contain' based on your preference */
	  /* Optionally, you can add more CSS properties such as background-position */
	  background-position: center;
            background-size: cover;
            padding-top: 45px;
	  }
	  .login-form {
            background: #5e9fba7a;
            margin-top: 50px;
            margin-bottom: 100px;
            padding: 100px;
            border-radius: 50px;
            box-shadow: 10px 10px 5px 2px rgb(0, 42, 84);
        }
  h1 {
  font-size: 70px;
  text-align: center;
  font-weight: 520;
  color: #062c38;
  }
    </style>
</head>
<body>
    <h1>LOGIN</h1>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="login-form">
                   
                    <form method="post" action="{% url 'login_view' %}">
                    {% csrf_token %}
                    <div class="form-group">

        <label for="username" style="color: azure; font-size:20px ;">Username:</label>
        <input type="text" id="username" name="username" class="form-control" placeholder="enter the username" required></div>
        <div class="form-group">

        <label for="password" style="color: azure;font-size:20px ;">Password:</label>
        <input type="password" id="password" name="password" class="form-control" name="password" placeholder="enter the password" required><br>
        <button type="submit" class = "btn  form-control btn-primary" style="color: rgb(3, 7, 11);">Login</button>
    </form>
    {% if error_message %}
        <p style="color: red;">{{ error_message }}</p>
    {% endif %}
</body>
</html>

newapp/templates/planedit.html


{% extends 'layout/app-layout.html' %}
{% block 'content' %}
{%load static %}
<style>
    h1{
    font-size: 45px;
    text-align: center;
    font-weight: 120;
   
    font-family:'Times New Roman', Times, serif;
     color: #2a2443;
    }
</style>
<br>
<a href="{% url 'planlists' %}" class="btn btn-dark">back</a>

<h1>
    Hello! Lets,edit plans
</h1>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="login-form">
               
                <form method="post" action="">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_title" style="color: azure;font-size:20px ;">Title:</label>
                    <input type="text" name="title" class="form-control" value="{{product.title}}" maxlength="150" required="" id="id_title">
                    </div>
                   <div class="form-group">
                    <label for="id_duration" style="color: azure;font-size:20px ;">Duration:</label>
                    <input type="text" name="duration" class="form-control" value="{{product.duration}}" maxlength="150" required="" id="id_duration">
                </div>                    
                <div class="form-group">
                    <label for="id_description" style="color: azure;font-size:20px ;">Description:</label>
                <textarea name="description" cols="40" rows="1" class="form-control" maxlength="1200" required="" id="id_description">{{product.description}}</textarea>
                    </div>
                <div class="form-group">
                    <label for="id_price">Price:</label>
                    <input type="number" name="price" value="{{product.price}}"  required="" id="id_price">
                    </div>
                                                           
                <button type = "submit" class = "btn  form-control btn-primary" value="update" style="color: rgb(3, 7, 11);" >Submit</button>    </form>




{%endblock%}

newapp/templates/planlists.html
{% extends 'layout/app-layout.html' %}
{% block 'content' %}
<style>
    h1 {
        font-size: 45px;
        text-align: center;
        font-weight: 120;
        font-family: 'Times New Roman', Times, serif;
        color: #2a2443;
    }
</style>

<h1>Plans</h1>
<div class="container">
    <div class="row">
        {% for plan in plans %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ plan.title }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted"><strong>{{ plan.duration }} Days</strong></h6>
                    <p class="card-text">{{ plan.description }}</p>
                    <p class="card-text"><strong>Price:</strong> {{ plan.price }}</p>
                    <a href="{% url 'planedit' plan.id %}" class="btn btn-success">EDIT</a>
                    <button data-toggle="modal" data-target="#myModal{{ plan.id }}" class="btn btn-danger delete-btn">Delete</button>
                </div>
            </div>
            <div class="modal fade" id="myModal{{ plan.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <form id="deleteForm{{ plan.id }}" method="post" action="{% url 'deleteplan' plan.id %}">
                            {% csrf_token %}
                            <div class="modal-header">
                                <h5 class="modal-title" id="myModalLabel">Confirm Delete</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Are you sure you want to delete "{{ plan.title }}"?
                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-danger">Delete</button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

newapp/templates/reveniew.html
{% extends 'layout/app-layout.html' %}
{% block 'content' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Videos</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <style>
        h1 {
            font-size: 35px;
            text-align: center;
            font-weight: 520;
            margin-top: -50px;
            font-family: 'Times New Roman', Times, serif;
            color: #2a2443;
        }
        .pagination .page-item .page-link {
            color: #fff;
            background-color: #343a40;
            border-color: #343a40;
        }

        .pagination .page-item.active .page-link {
            color: #fff;
            background-color: #007bff;
            border-color: #007bff;
        }

        .pagination .page-item .page-link:hover {
            color: #fff;
            background-color: #6c757d;
            border-color: #6c757d;
        }
    </style>
</head>
<body>
<div class="container mt-5">
    <br><br>
    <h1>REVENIEW</h1>
    <div>
        <form method="GET">
            <div>
                From: <input type="date" name="start_date" value="{{ start_date }}">
                To: <input type="date" name="end_date" value="{{ end_date }}">
                <button type="submit" class="btn btn-primary">Filter</button>
            </div>
        </form></div><br>
    <table class="table table-bordered table-responsive-md">
        <thead class="thead-dark">
            <tr>
                <th>Plan</th>
                <th>Price</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            {%for sub in page_obj %}
            <tr>
                <td>{{sub.plan.title}}</td>
                <td>{{sub.plan.price}}</td>
                <td>{{sub.subscribed_at}}</td> </tr>
            {% endfor %}
            <tr>
                <td colspan="2"><strong>Total Amount</strong></td>
                <td><strong>{{ total_amount }}</strong></td>
            </tr>
        </tbody>
    </table>
    <p></p>
    <nav aria-label="Page navigation example" class="navbar navbar-expand-lg" >
        <ul class="pagination mx-auto" >
            {% if page_obj.has_previous %}
            <li class="page-item" >
                <a class="page-link" href="?page=1" >&laquo; First</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
            {% endif %}
            {% for page_number in page_obj.paginator.get_elided_page_range %}
            {% if page_obj.number == page_number %}
            <li class="page-item active">
                <span class="page-link">{{ page_number }} <span class="sr-only">(current)</span></span>
            </li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a></li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>
</body>
</html>
{% endblock %}

newapp/templates/subscriberlist.html
{% extends 'layout/app-layout.html' %}
{% block 'content' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Videos</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <style>
        h1 {
            font-size: 35px;
            text-align: center;
            font-weight: 520;
            margin-top: -50px;
            font-family: 'Times New Roman', Times, serif;
            color: #2a2443;
        }
        .pagination .page-item .page-link {
            color: #fff;
            background-color: #343a40;
            border-color: #343a40;
        }

        .pagination .page-item.active .page-link {
            color: #fff;
            background-color: #007bff;
            border-color: #007bff;
        }

        .pagination .page-item .page-link:hover {
            color: #fff;
            background-color: #6c757d;
            border-color: #6c757d;
        }
    </style>
</head>
<body>
<div class="container mt-5">
    <br><br>
    <h1>SUBSCRIBERS LIST</h1>
    <br><br>

    <form action="{% url 'subscriberlist' %}" method="GET">
        <input type="text" name="query" class="form mb-3"style="color: rgb(15, 86, 86); font-size: 20px;" value="{{ query }}" placeholder="Search...">
        <button type="submit" class="btn-md btn-success">Search</button>
    </form>    
    <div>

        <form method="GET">
            <div>
                From: <input type="date" name="start_date" value="{{ start_date }}">
                To: <input type="date" name="end_date" value="{{ end_date }}">
                <button type="submit" class="btn btn-primary">Filter</button>
            </div>
        </form></div><br>
    <table class="table table-bordered table-responsive-md">
        <thead class="thead-dark">
            <tr>
                <th>Username</th>
                <th>Plan Name</th>
                <th>SubscribedDate</th>
                <th>OrderId</th>
                <th>Expiry Date</th>
                <th>Price</th>
                
            </tr>
        </thead>
        <tbody>
            {%for sub in page_obj %}
            <tr>
                <td>{{sub.user.username}}</td>
                <td>{{sub.plan.title}}</td>
                <td>{{sub.subscribed_at}}</td>
                <td>{{sub.order_id}}</td>
                <td>{{sub.ExpiryDate}}</td>
                <td>{{sub.plan.price}}</td>
                <!-- Add this wherever you want to display the total amount -->

            
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <p></p>
    <nav aria-label="Page navigation example" class="navbar navbar-expand-lg" >
        <ul class="pagination mx-auto" >
            {% if page_obj.has_previous %}
            <li class="page-item" >
                <a class="page-link" href="?page=1" >&laquo; First</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
            {% endif %}
            {% for page_number in page_obj.paginator.get_elided_page_range %}
            {% if page_obj.number == page_number %}
            <li class="page-item active">
                <span class="page-link">{{ page_number }} <span class="sr-only">(current)</span></span>
            </li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a></li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
            </li>
            {% endif %}
        </ul>
    </nav>

</div>
</body>
</html>
{% endblock %}